

pymodbus 3.6.4

https://stackoverflow.com/questions/77509935/pymodbus-modbus-error-input-output-no-response-received-from-the-remote-sla
https://github.com/pymodbus-dev/pymodbus/issues/2083

2024-03-16 16:10:22,763 logging.py:103 - DEBUG - Adding transaction 115
2024-03-16 16:10:22,763 logging.py:103 - DEBUG - send: 0x73 0x4 0x0 0x40 0x0 0x16 0x7a 0xc2
2024-03-16 16:10:22,840 logging.py:103 - DEBUG - recv: 0x73 0x4 0x2c 0x27 0x10 0x0 0x65 0x0 0x1 0x4 0xb0 0x0 0x2a 0x0 0x0 0x0 0x0 0x0 0x0 0x73 0x25 0x73 0x19 0x73 0x19 0x73 0x1f 0x73 0x19 0x73 0x1f 0x0 0x0 0x0 0x0 0x0 0x64 0x0 0x64 0x0 0x64 0x0 0x64 0x0 0x64 0x0 0x64 0x91 0xad old_data:  addr=None
2024-03-16 16:10:22,840 logging.py:103 - DEBUG - Processing: 0x73 0x4 0x2c 0x27 0x10 0x0 0x65 0x0 0x1 0x4 0xb0 0x0 0x2a 0x0 0x0 0x0 0x0 0x0 0x0 0x73 0x25 0x73 0x19 0x73 0x19 0x73 0x1f 0x73 0x19 0x73 0x1f 0x0 0x0 0x0 0x0 0x0 0x64 0x0 0x64 0x0 0x64 0x0 0x64 0x0 0x64 0x0 0x64 0x91 0xad
2024-03-16 16:10:22,841 logging.py:103 - DEBUG - Frame check failed, ignoring!!
2024-03-16 16:10:22,841 logging.py:103 - DEBUG - Resetting frame - Current Frame in buffer - 0x72 0x4 0x2c 0x27 0x10 0x0 0x65 0x0 0x1 0x4 0xb0 0x0 0x2a 0x0 0x0 0x0 0x0 0x0 0x0 0x73 0x2c 0x73 0x32 0x73 0x2c 0x73 0x38 0x73 0x32 0x73 0x2c 0x0 0x0 0x0 0x0 0x0 0x64 0x0 0x64 0x0 0x64 0x0 0x64 0x0 0x64 0xc0 0x73 0x4 0x2c 0x27 0x10 0x0 0x65 0x0 0x1 0x4 0xb0 0x0 0x2a 0x0 0x0 0x0 0x0 0x0 0x0 0x73 0x25 0x73 0x19 0x73 0x19 0x73 0x1f 0x73 0x19 0x73 0x1f 0x0 0x0 0x0 0x0 0x0 0x64 0x0 0x64 0x0 0x64 0x0 0x64 0x0 0x64 0x0 0x64 0x91 0xad
2024-03-16 16:10:22,841 logging.py:103 - DEBUG - Frame check failed, ignoring!!
2024-03-16 16:10:22,841 logging.py:103 - DEBUG - Resetting frame - Current Frame in buffer - 0x27 0x10 0x0 0x65 0x0 0x1 0x4 0xb0 0x0 0x2a 0x0 0x0 0x0 0x0 0x0 0x0 0x73 0x2c 0x73 0x32 0x73 0x2c 0x73 0x38 0x73 0x32 0x73 0x2c 0x0 0x0 0x0 0x0 0x0 0x64 0x0 0x64 0x0 0x64 0x0 0x64 0x0 0x64 0xc0 0x73 0x4 0x2c 0x27 0x10 0x0 0x65 0x0 0x1 0x4 0xb0 0x0 0x2a 0x0 0x0 0x0 0x0 0x0 0x0 0x73 0x25 0x73 0x19 0x73 0x19 0x73 0x1f 0x73 0x19 0x73 0x1f 0x0 0x0 0x0 0x0 0x0 0x64 0x0 0x64 0x0 0x64 0x0 0x64 0x0 0x64 0x0 0x64 0x91 0xad
2024-03-16 16:10:22,841 logging.py:103 - DEBUG - Frame check failed, ignoring!!
2024-03-16 16:10:22,841 logging.py:103 - DEBUG - Resetting frame - Current Frame in buffer - 0x0 0x1 0x4 0xb0 0x0 0x2a 0x0 0x0 0x0 0x0 0x0 0x0 0x73 0x2c 0x73 0x32 0x73 0x2c 0x73 0x38 0x73 0x32 0x73 0x2c 0x0 0x0 0x0 0x0 0x0 0x64 0x0 0x64 0x0 0x64 0x0 0x64 0x0 0x64 0xc0 0x73 0x4 0x2c 0x27 0x10 0x0 0x65 0x0 0x1 0x4 0xb0 0x0 0x2a 0x0 0x0 0x0 0x0 0x0 0x0 0x73 0x25 0x73 0x19 0x73 0x19 0x73 0x1f 0x73 0x19 0x73 0x1f 0x0 0x0 0x0 0x0 0x0 0x64 0x0 0x64 0x0 0x64 0x0 0x64 0x0 0x64 0x0 0x64 0x91 0xad
2024-03-16 16:10:22,842 logging.py:103 - DEBUG - Frame - not ready
2024-03-16 16:10:22,864 logging.py:103 - DEBUG - Adding transaction 115




2024-03-16 16:11:20,312 util_modbus_haus.py:81 - ERROR - Haus 14(modbus=114): ModbusIOException('[Input/Output] ERROR: No response received after 1 retries')
2024-03-16 16:11:20,313 utils_logger.py:22 - DEBUG - HsmHaus14: SignalModbusFailed: will be handled by ok
2024-03-16 16:11:20,313 utils_logger.py:19 - DEBUG - HsmHaus14:   calling state "state_ok(SignalModbusFailed)"
2024-03-16 16:11:20,313 utils_logger.py:19 - DEBUG - HsmHaus14:   No state change!


